### ISSUE TITLE
Features needed to make perfect editor

### ISSUE THREAD

**Issue by arunjoshtech** [Tsuzat/ShadEditor#1]
Dear team, 
it is my humble request, If you are trying to make web richtext editor make it really well enough to use. 
Auto capitalisation 
Line space adjustment 
which really make sense else this project is like reinveting of wheel.

**Comment by Tsuzat** [comment]
Dear @arunjoshtech,

It's my humble request to read documentation first. This is not a "web richtext editor" for **typical users**. This is a component based editor like shadcn ui, which copies the component in your project and let's you do whatever you want. This "editor component" is made for "**svelte developers**" who are developing an application using [shadcn](https://www.shadcn-svelte.com/) to provide them a rich and featurefull editor (which they can extend to any limit and in any direction they want, just like shadcn ui). 

If you want to extend it with "Auto capitalisation" and "Line space adjustment", implement it in your own project. You want collaboration?? Implement it in your project using whatever you want with [tiptap](https://tiptap.dev/) integration.

>which really make sense else this project is like reinveting of wheel.

It is. This project is for very specific **`developers`**, who are using svelte(kit), shadcn ui and tailwind. This project, takes the barebone `tiptap` editor, and provides the **opinionated shadcn ui** version of an editor (as a component for developers to use it in their project, so that they do not have to set it up from scratch). Tiptap usages [Prosemirror](https://prosemirror.net/) under the hood. So, `it is like reinveting of wheel`.

There is no editor (to my knowledge) which is component based like this project. Most of the editor provide API's and components to use, but, again, this project copies the whole "editor" component's code to your project. Do whatever you want with it or use it as default.

Thanks for your time and Happy Coding ❤️
